import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Nav } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tanzania Travel Review (TTR)",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="opacity-100">
      <body className={inter.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
